/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerIndexRouteImport } from './routes/trainer.index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrainerProfileRouteImport } from './routes/trainer.profile'
import { Route as TrainerCalendarRouteImport } from './routes/trainer.calendar'
import { Route as TrainerAttendanceRouteImport } from './routes/trainer.attendance'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminUpdationRouteImport } from './routes/super-admin.updation'
import { Route as SuperAdminTrainersRouteImport } from './routes/super-admin.trainers'
import { Route as SuperAdminTrainerAttendanceRequestRouteImport } from './routes/super-admin.trainer-attendance-request'
import { Route as SuperAdminTrainerAttendanceRouteImport } from './routes/super-admin.trainer-attendance'
import { Route as SuperAdminStudentsRouteImport } from './routes/super-admin.students'
import { Route as SuperAdminSlotsRouteImport } from './routes/super-admin.slots'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminRolesRouteImport } from './routes/super-admin.roles'
import { Route as SuperAdminReportsRouteImport } from './routes/super-admin.reports'
import { Route as SuperAdminRegistrationsRouteImport } from './routes/super-admin.registrations'
import { Route as SuperAdminProfileRouteImport } from './routes/super-admin.profile'
import { Route as SuperAdminPaymentsRouteImport } from './routes/super-admin.payments'
import { Route as SuperAdminNotificationsRouteImport } from './routes/super-admin.notifications'
import { Route as SuperAdminCoursesRouteImport } from './routes/super-admin.courses'
import { Route as SuperAdminCitiesRouteImport } from './routes/super-admin.cities'
import { Route as SuperAdminCampusesRouteImport } from './routes/super-admin.campuses'
import { Route as SuperAdminBatchesRouteImport } from './routes/super-admin.batches'
import { Route as SuperAdminAttendanceRouteImport } from './routes/super-admin.attendance'
import { Route as SuperAdminAdministrationRouteImport } from './routes/super-admin.administration'
import { Route as SuperAdminActivityRouteImport } from './routes/super-admin.activity'
import { Route as StudentQuizRouteImport } from './routes/student.quiz'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentPaymentRouteImport } from './routes/student.payment'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentAssignmentRouteImport } from './routes/student.assignment'
import { Route as AdminUpdationRouteImport } from './routes/admin.updation'
import { Route as AdminTrainersRouteImport } from './routes/admin.trainers'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSlotsRouteImport } from './routes/admin.slots'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as SuperAdminAttendanceViewRouteImport } from './routes/super-admin.attendance.view'
import { Route as AdminTrainerAttendanceMarkRouteImport } from './routes/admin.trainer-attendance.mark'
import { Route as AdminAttendanceViewRouteImport } from './routes/admin.attendance.view'

const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerRoute,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrainerProfileRoute = TrainerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerCalendarRoute = TrainerCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerAttendanceRoute = TrainerAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TrainerRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminUpdationRoute = SuperAdminUpdationRouteImport.update({
  id: '/updation',
  path: '/updation',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminTrainersRoute = SuperAdminTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminTrainerAttendanceRequestRoute =
  SuperAdminTrainerAttendanceRequestRouteImport.update({
    id: '/trainer-attendance-request',
    path: '/trainer-attendance-request',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminTrainerAttendanceRoute =
  SuperAdminTrainerAttendanceRouteImport.update({
    id: '/trainer-attendance',
    path: '/trainer-attendance',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminStudentsRoute = SuperAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSlotsRoute = SuperAdminSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminRolesRoute = SuperAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminReportsRoute = SuperAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminRegistrationsRoute = SuperAdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminProfileRoute = SuperAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPaymentsRoute = SuperAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminNotificationsRoute = SuperAdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminCoursesRoute = SuperAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminCitiesRoute = SuperAdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminCampusesRoute = SuperAdminCampusesRouteImport.update({
  id: '/campuses',
  path: '/campuses',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminBatchesRoute = SuperAdminBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAttendanceRoute = SuperAdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAdministrationRoute =
  SuperAdminAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminActivityRoute = SuperAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SuperAdminRoute,
} as any)
const StudentQuizRoute = StudentQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPaymentRoute = StudentPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentRoute = StudentAssignmentRouteImport.update({
  id: '/assignment',
  path: '/assignment',
  getParentRoute: () => StudentRoute,
} as any)
const AdminUpdationRoute = AdminUpdationRouteImport.update({
  id: '/updation',
  path: '/updation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainersRoute = AdminTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlotsRoute = AdminSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const SuperAdminAttendanceViewRoute =
  SuperAdminAttendanceViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => SuperAdminAttendanceRoute,
  } as any)
const AdminTrainerAttendanceMarkRoute =
  AdminTrainerAttendanceMarkRouteImport.update({
    id: '/trainer-attendance/mark',
    path: '/trainer-attendance/mark',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAttendanceViewRoute = AdminAttendanceViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => AdminAttendanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/trainer': typeof TrainerRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/admin/updation': typeof AdminUpdationRoute
  '/student/assignment': typeof StudentAssignmentRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/payment': typeof StudentPaymentRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/quiz': typeof StudentQuizRoute
  '/super-admin/activity': typeof SuperAdminActivityRoute
  '/super-admin/administration': typeof SuperAdminAdministrationRoute
  '/super-admin/attendance': typeof SuperAdminAttendanceRouteWithChildren
  '/super-admin/batches': typeof SuperAdminBatchesRoute
  '/super-admin/campuses': typeof SuperAdminCampusesRoute
  '/super-admin/cities': typeof SuperAdminCitiesRoute
  '/super-admin/courses': typeof SuperAdminCoursesRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/profile': typeof SuperAdminProfileRoute
  '/super-admin/registrations': typeof SuperAdminRegistrationsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/slots': typeof SuperAdminSlotsRoute
  '/super-admin/students': typeof SuperAdminStudentsRoute
  '/super-admin/trainer-attendance': typeof SuperAdminTrainerAttendanceRoute
  '/super-admin/trainer-attendance-request': typeof SuperAdminTrainerAttendanceRequestRoute
  '/super-admin/trainers': typeof SuperAdminTrainersRoute
  '/super-admin/updation': typeof SuperAdminUpdationRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/trainer/attendance': typeof TrainerAttendanceRoute
  '/trainer/calendar': typeof TrainerCalendarRoute
  '/trainer/profile': typeof TrainerProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/admin/attendance/view': typeof AdminAttendanceViewRoute
  '/admin/trainer-attendance/mark': typeof AdminTrainerAttendanceMarkRoute
  '/super-admin/attendance/view': typeof SuperAdminAttendanceViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/attendance': typeof AdminAttendanceRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/admin/updation': typeof AdminUpdationRoute
  '/student/assignment': typeof StudentAssignmentRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/payment': typeof StudentPaymentRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/quiz': typeof StudentQuizRoute
  '/super-admin/activity': typeof SuperAdminActivityRoute
  '/super-admin/administration': typeof SuperAdminAdministrationRoute
  '/super-admin/attendance': typeof SuperAdminAttendanceRouteWithChildren
  '/super-admin/batches': typeof SuperAdminBatchesRoute
  '/super-admin/campuses': typeof SuperAdminCampusesRoute
  '/super-admin/cities': typeof SuperAdminCitiesRoute
  '/super-admin/courses': typeof SuperAdminCoursesRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/profile': typeof SuperAdminProfileRoute
  '/super-admin/registrations': typeof SuperAdminRegistrationsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/slots': typeof SuperAdminSlotsRoute
  '/super-admin/students': typeof SuperAdminStudentsRoute
  '/super-admin/trainer-attendance': typeof SuperAdminTrainerAttendanceRoute
  '/super-admin/trainer-attendance-request': typeof SuperAdminTrainerAttendanceRequestRoute
  '/super-admin/trainers': typeof SuperAdminTrainersRoute
  '/super-admin/updation': typeof SuperAdminUpdationRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/trainer/attendance': typeof TrainerAttendanceRoute
  '/trainer/calendar': typeof TrainerCalendarRoute
  '/trainer/profile': typeof TrainerProfileRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/trainer': typeof TrainerIndexRoute
  '/admin/attendance/view': typeof AdminAttendanceViewRoute
  '/admin/trainer-attendance/mark': typeof AdminTrainerAttendanceMarkRoute
  '/super-admin/attendance/view': typeof SuperAdminAttendanceViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/trainer': typeof TrainerRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/slots': typeof AdminSlotsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/admin/updation': typeof AdminUpdationRoute
  '/student/assignment': typeof StudentAssignmentRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/payment': typeof StudentPaymentRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/quiz': typeof StudentQuizRoute
  '/super-admin/activity': typeof SuperAdminActivityRoute
  '/super-admin/administration': typeof SuperAdminAdministrationRoute
  '/super-admin/attendance': typeof SuperAdminAttendanceRouteWithChildren
  '/super-admin/batches': typeof SuperAdminBatchesRoute
  '/super-admin/campuses': typeof SuperAdminCampusesRoute
  '/super-admin/cities': typeof SuperAdminCitiesRoute
  '/super-admin/courses': typeof SuperAdminCoursesRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/profile': typeof SuperAdminProfileRoute
  '/super-admin/registrations': typeof SuperAdminRegistrationsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/slots': typeof SuperAdminSlotsRoute
  '/super-admin/students': typeof SuperAdminStudentsRoute
  '/super-admin/trainer-attendance': typeof SuperAdminTrainerAttendanceRoute
  '/super-admin/trainer-attendance-request': typeof SuperAdminTrainerAttendanceRequestRoute
  '/super-admin/trainers': typeof SuperAdminTrainersRoute
  '/super-admin/updation': typeof SuperAdminUpdationRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/trainer/attendance': typeof TrainerAttendanceRoute
  '/trainer/calendar': typeof TrainerCalendarRoute
  '/trainer/profile': typeof TrainerProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/admin/attendance/view': typeof AdminAttendanceViewRoute
  '/admin/trainer-attendance/mark': typeof AdminTrainerAttendanceMarkRoute
  '/super-admin/attendance/view': typeof SuperAdminAttendanceViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/super-admin'
    | '/trainer'
    | '/admin/attendance'
    | '/admin/profile'
    | '/admin/slots'
    | '/admin/students'
    | '/admin/trainers'
    | '/admin/updation'
    | '/student/assignment'
    | '/student/attendance'
    | '/student/payment'
    | '/student/profile'
    | '/student/progress'
    | '/student/quiz'
    | '/super-admin/activity'
    | '/super-admin/administration'
    | '/super-admin/attendance'
    | '/super-admin/batches'
    | '/super-admin/campuses'
    | '/super-admin/cities'
    | '/super-admin/courses'
    | '/super-admin/notifications'
    | '/super-admin/payments'
    | '/super-admin/profile'
    | '/super-admin/registrations'
    | '/super-admin/reports'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/slots'
    | '/super-admin/students'
    | '/super-admin/trainer-attendance'
    | '/super-admin/trainer-attendance-request'
    | '/super-admin/trainers'
    | '/super-admin/updation'
    | '/super-admin/users'
    | '/trainer/attendance'
    | '/trainer/calendar'
    | '/trainer/profile'
    | '/admin/'
    | '/student/'
    | '/super-admin/'
    | '/trainer/'
    | '/admin/attendance/view'
    | '/admin/trainer-attendance/mark'
    | '/super-admin/attendance/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/attendance'
    | '/admin/profile'
    | '/admin/slots'
    | '/admin/students'
    | '/admin/trainers'
    | '/admin/updation'
    | '/student/assignment'
    | '/student/attendance'
    | '/student/payment'
    | '/student/profile'
    | '/student/progress'
    | '/student/quiz'
    | '/super-admin/activity'
    | '/super-admin/administration'
    | '/super-admin/attendance'
    | '/super-admin/batches'
    | '/super-admin/campuses'
    | '/super-admin/cities'
    | '/super-admin/courses'
    | '/super-admin/notifications'
    | '/super-admin/payments'
    | '/super-admin/profile'
    | '/super-admin/registrations'
    | '/super-admin/reports'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/slots'
    | '/super-admin/students'
    | '/super-admin/trainer-attendance'
    | '/super-admin/trainer-attendance-request'
    | '/super-admin/trainers'
    | '/super-admin/updation'
    | '/super-admin/users'
    | '/trainer/attendance'
    | '/trainer/calendar'
    | '/trainer/profile'
    | '/admin'
    | '/student'
    | '/super-admin'
    | '/trainer'
    | '/admin/attendance/view'
    | '/admin/trainer-attendance/mark'
    | '/super-admin/attendance/view'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/super-admin'
    | '/trainer'
    | '/admin/attendance'
    | '/admin/profile'
    | '/admin/slots'
    | '/admin/students'
    | '/admin/trainers'
    | '/admin/updation'
    | '/student/assignment'
    | '/student/attendance'
    | '/student/payment'
    | '/student/profile'
    | '/student/progress'
    | '/student/quiz'
    | '/super-admin/activity'
    | '/super-admin/administration'
    | '/super-admin/attendance'
    | '/super-admin/batches'
    | '/super-admin/campuses'
    | '/super-admin/cities'
    | '/super-admin/courses'
    | '/super-admin/notifications'
    | '/super-admin/payments'
    | '/super-admin/profile'
    | '/super-admin/registrations'
    | '/super-admin/reports'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/slots'
    | '/super-admin/students'
    | '/super-admin/trainer-attendance'
    | '/super-admin/trainer-attendance-request'
    | '/super-admin/trainers'
    | '/super-admin/updation'
    | '/super-admin/users'
    | '/trainer/attendance'
    | '/trainer/calendar'
    | '/trainer/profile'
    | '/admin/'
    | '/student/'
    | '/super-admin/'
    | '/trainer/'
    | '/admin/attendance/view'
    | '/admin/trainer-attendance/mark'
    | '/super-admin/attendance/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  TrainerRoute: typeof TrainerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trainer/profile': {
      id: '/trainer/profile'
      path: '/profile'
      fullPath: '/trainer/profile'
      preLoaderRoute: typeof TrainerProfileRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/calendar': {
      id: '/trainer/calendar'
      path: '/calendar'
      fullPath: '/trainer/calendar'
      preLoaderRoute: typeof TrainerCalendarRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/attendance': {
      id: '/trainer/attendance'
      path: '/attendance'
      fullPath: '/trainer/attendance'
      preLoaderRoute: typeof TrainerAttendanceRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/updation': {
      id: '/super-admin/updation'
      path: '/updation'
      fullPath: '/super-admin/updation'
      preLoaderRoute: typeof SuperAdminUpdationRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/trainers': {
      id: '/super-admin/trainers'
      path: '/trainers'
      fullPath: '/super-admin/trainers'
      preLoaderRoute: typeof SuperAdminTrainersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/trainer-attendance-request': {
      id: '/super-admin/trainer-attendance-request'
      path: '/trainer-attendance-request'
      fullPath: '/super-admin/trainer-attendance-request'
      preLoaderRoute: typeof SuperAdminTrainerAttendanceRequestRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/trainer-attendance': {
      id: '/super-admin/trainer-attendance'
      path: '/trainer-attendance'
      fullPath: '/super-admin/trainer-attendance'
      preLoaderRoute: typeof SuperAdminTrainerAttendanceRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/students': {
      id: '/super-admin/students'
      path: '/students'
      fullPath: '/super-admin/students'
      preLoaderRoute: typeof SuperAdminStudentsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/slots': {
      id: '/super-admin/slots'
      path: '/slots'
      fullPath: '/super-admin/slots'
      preLoaderRoute: typeof SuperAdminSlotsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/roles': {
      id: '/super-admin/roles'
      path: '/roles'
      fullPath: '/super-admin/roles'
      preLoaderRoute: typeof SuperAdminRolesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/reports': {
      id: '/super-admin/reports'
      path: '/reports'
      fullPath: '/super-admin/reports'
      preLoaderRoute: typeof SuperAdminReportsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/registrations': {
      id: '/super-admin/registrations'
      path: '/registrations'
      fullPath: '/super-admin/registrations'
      preLoaderRoute: typeof SuperAdminRegistrationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/profile': {
      id: '/super-admin/profile'
      path: '/profile'
      fullPath: '/super-admin/profile'
      preLoaderRoute: typeof SuperAdminProfileRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/payments': {
      id: '/super-admin/payments'
      path: '/payments'
      fullPath: '/super-admin/payments'
      preLoaderRoute: typeof SuperAdminPaymentsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/notifications': {
      id: '/super-admin/notifications'
      path: '/notifications'
      fullPath: '/super-admin/notifications'
      preLoaderRoute: typeof SuperAdminNotificationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/courses': {
      id: '/super-admin/courses'
      path: '/courses'
      fullPath: '/super-admin/courses'
      preLoaderRoute: typeof SuperAdminCoursesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/cities': {
      id: '/super-admin/cities'
      path: '/cities'
      fullPath: '/super-admin/cities'
      preLoaderRoute: typeof SuperAdminCitiesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/campuses': {
      id: '/super-admin/campuses'
      path: '/campuses'
      fullPath: '/super-admin/campuses'
      preLoaderRoute: typeof SuperAdminCampusesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/batches': {
      id: '/super-admin/batches'
      path: '/batches'
      fullPath: '/super-admin/batches'
      preLoaderRoute: typeof SuperAdminBatchesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/attendance': {
      id: '/super-admin/attendance'
      path: '/attendance'
      fullPath: '/super-admin/attendance'
      preLoaderRoute: typeof SuperAdminAttendanceRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/administration': {
      id: '/super-admin/administration'
      path: '/administration'
      fullPath: '/super-admin/administration'
      preLoaderRoute: typeof SuperAdminAdministrationRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/activity': {
      id: '/super-admin/activity'
      path: '/activity'
      fullPath: '/super-admin/activity'
      preLoaderRoute: typeof SuperAdminActivityRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/student/quiz': {
      id: '/student/quiz'
      path: '/quiz'
      fullPath: '/student/quiz'
      preLoaderRoute: typeof StudentQuizRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/payment': {
      id: '/student/payment'
      path: '/payment'
      fullPath: '/student/payment'
      preLoaderRoute: typeof StudentPaymentRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignment': {
      id: '/student/assignment'
      path: '/assignment'
      fullPath: '/student/assignment'
      preLoaderRoute: typeof StudentAssignmentRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/updation': {
      id: '/admin/updation'
      path: '/updation'
      fullPath: '/admin/updation'
      preLoaderRoute: typeof AdminUpdationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trainers': {
      id: '/admin/trainers'
      path: '/trainers'
      fullPath: '/admin/trainers'
      preLoaderRoute: typeof AdminTrainersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/slots': {
      id: '/admin/slots'
      path: '/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AdminSlotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/super-admin/attendance/view': {
      id: '/super-admin/attendance/view'
      path: '/view'
      fullPath: '/super-admin/attendance/view'
      preLoaderRoute: typeof SuperAdminAttendanceViewRouteImport
      parentRoute: typeof SuperAdminAttendanceRoute
    }
    '/admin/trainer-attendance/mark': {
      id: '/admin/trainer-attendance/mark'
      path: '/trainer-attendance/mark'
      fullPath: '/admin/trainer-attendance/mark'
      preLoaderRoute: typeof AdminTrainerAttendanceMarkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance/view': {
      id: '/admin/attendance/view'
      path: '/view'
      fullPath: '/admin/attendance/view'
      preLoaderRoute: typeof AdminAttendanceViewRouteImport
      parentRoute: typeof AdminAttendanceRoute
    }
  }
}

interface AdminAttendanceRouteChildren {
  AdminAttendanceViewRoute: typeof AdminAttendanceViewRoute
}

const AdminAttendanceRouteChildren: AdminAttendanceRouteChildren = {
  AdminAttendanceViewRoute: AdminAttendanceViewRoute,
}

const AdminAttendanceRouteWithChildren = AdminAttendanceRoute._addFileChildren(
  AdminAttendanceRouteChildren,
)

interface AdminRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSlotsRoute: typeof AdminSlotsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTrainersRoute: typeof AdminTrainersRoute
  AdminUpdationRoute: typeof AdminUpdationRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTrainerAttendanceMarkRoute: typeof AdminTrainerAttendanceMarkRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminSlotsRoute: AdminSlotsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTrainersRoute: AdminTrainersRoute,
  AdminUpdationRoute: AdminUpdationRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTrainerAttendanceMarkRoute: AdminTrainerAttendanceMarkRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAssignmentRoute: typeof StudentAssignmentRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentPaymentRoute: typeof StudentPaymentRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentQuizRoute: typeof StudentQuizRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssignmentRoute: StudentAssignmentRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentPaymentRoute: StudentPaymentRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentQuizRoute: StudentQuizRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface SuperAdminAttendanceRouteChildren {
  SuperAdminAttendanceViewRoute: typeof SuperAdminAttendanceViewRoute
}

const SuperAdminAttendanceRouteChildren: SuperAdminAttendanceRouteChildren = {
  SuperAdminAttendanceViewRoute: SuperAdminAttendanceViewRoute,
}

const SuperAdminAttendanceRouteWithChildren =
  SuperAdminAttendanceRoute._addFileChildren(SuperAdminAttendanceRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminActivityRoute: typeof SuperAdminActivityRoute
  SuperAdminAdministrationRoute: typeof SuperAdminAdministrationRoute
  SuperAdminAttendanceRoute: typeof SuperAdminAttendanceRouteWithChildren
  SuperAdminBatchesRoute: typeof SuperAdminBatchesRoute
  SuperAdminCampusesRoute: typeof SuperAdminCampusesRoute
  SuperAdminCitiesRoute: typeof SuperAdminCitiesRoute
  SuperAdminCoursesRoute: typeof SuperAdminCoursesRoute
  SuperAdminNotificationsRoute: typeof SuperAdminNotificationsRoute
  SuperAdminPaymentsRoute: typeof SuperAdminPaymentsRoute
  SuperAdminProfileRoute: typeof SuperAdminProfileRoute
  SuperAdminRegistrationsRoute: typeof SuperAdminRegistrationsRoute
  SuperAdminReportsRoute: typeof SuperAdminReportsRoute
  SuperAdminRolesRoute: typeof SuperAdminRolesRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminSlotsRoute: typeof SuperAdminSlotsRoute
  SuperAdminStudentsRoute: typeof SuperAdminStudentsRoute
  SuperAdminTrainerAttendanceRoute: typeof SuperAdminTrainerAttendanceRoute
  SuperAdminTrainerAttendanceRequestRoute: typeof SuperAdminTrainerAttendanceRequestRoute
  SuperAdminTrainersRoute: typeof SuperAdminTrainersRoute
  SuperAdminUpdationRoute: typeof SuperAdminUpdationRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminActivityRoute: SuperAdminActivityRoute,
  SuperAdminAdministrationRoute: SuperAdminAdministrationRoute,
  SuperAdminAttendanceRoute: SuperAdminAttendanceRouteWithChildren,
  SuperAdminBatchesRoute: SuperAdminBatchesRoute,
  SuperAdminCampusesRoute: SuperAdminCampusesRoute,
  SuperAdminCitiesRoute: SuperAdminCitiesRoute,
  SuperAdminCoursesRoute: SuperAdminCoursesRoute,
  SuperAdminNotificationsRoute: SuperAdminNotificationsRoute,
  SuperAdminPaymentsRoute: SuperAdminPaymentsRoute,
  SuperAdminProfileRoute: SuperAdminProfileRoute,
  SuperAdminRegistrationsRoute: SuperAdminRegistrationsRoute,
  SuperAdminReportsRoute: SuperAdminReportsRoute,
  SuperAdminRolesRoute: SuperAdminRolesRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminSlotsRoute: SuperAdminSlotsRoute,
  SuperAdminStudentsRoute: SuperAdminStudentsRoute,
  SuperAdminTrainerAttendanceRoute: SuperAdminTrainerAttendanceRoute,
  SuperAdminTrainerAttendanceRequestRoute:
    SuperAdminTrainerAttendanceRequestRoute,
  SuperAdminTrainersRoute: SuperAdminTrainersRoute,
  SuperAdminUpdationRoute: SuperAdminUpdationRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

interface TrainerRouteChildren {
  TrainerAttendanceRoute: typeof TrainerAttendanceRoute
  TrainerCalendarRoute: typeof TrainerCalendarRoute
  TrainerProfileRoute: typeof TrainerProfileRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerAttendanceRoute: TrainerAttendanceRoute,
  TrainerCalendarRoute: TrainerCalendarRoute,
  TrainerProfileRoute: TrainerProfileRoute,
  TrainerIndexRoute: TrainerIndexRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  TrainerRoute: TrainerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
